const products = [
    {
        id: 1,
        manufacturer: 'apple',
        model: 'iphone 12 pro max',
        img: 'https://asset1.ee.co.uk/medias/iPhone-12-Pro-Max-PacificBlue-Mobile-480x864-1-Format-480?context=bWFzdGVyfHJvb3R8MjczODA2fGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaDY1L2hkZi85NTU1NDIzOTg1Njk0L2lQaG9uZV8xMl9Qcm9fTWF4X1BhY2lmaWNCbHVlX01vYmlsZV80ODB4ODY0XzFfRm9ybWF0LTQ4MHwzNzQ2NGYwZDg3MmUzNmJiNTk4MjQxYmNmMTQyNzY0Nzc2M2I2NzQ2MmFkNDFkZWE1ZjE2YjFmZmI3ZmRkMjk1',
        desc: '5G goes Pro. A14 Bionic rockets past every other smartphone chip. The Pro camera system takes low-light photography to the next level - with an even bigger jump on iPhone 12 Pro Max. And Ceramic Shield delivers four times better drop performance. Let’s see what this thing can do.',
        price: 1099.99,
    },
    {
        id: 2,
        manufacturer: 'apple',
        model: 'iphone 12 mini',
        img: 'https://asset1.ee.co.uk/medias/iphone-12-mini-5g-blue-mobile-detail-1-Format-480?context=bWFzdGVyfHJvb3R8MzA2MzU0fGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaGIyL2g0Ny85NTU1MzU3MzM1NTgyL2lwaG9uZS0xMi1taW5pLTVnLWJsdWUtbW9iaWxlLWRldGFpbC0xX0Zvcm1hdC00ODB8MzgxMGIwNGIyMzJlYmQyYmE4YWM4YzIwYzBiNjI0MjUyMmExMDZhMmZmZDAwZDViN2MwMDVlYzdhZDExMGU2Yw',
        desc: 'Apple Iphone 12 Mini 13.7 Cm (5.4) Dual Sim Ios 14 5g 64 Gb Blue iPhone 12 Blast past fast. 5G speed. A14 Bionic, the fastest chip in a smartphone. An edge-to-edge OLED display. Ceramic Shield with four times better drop performance. And Night mode on every camera. iPhone 12 has it all in two perfect sizes.',
        price: 699.99,
    },
    {
        id: 3,
        manufacturer: 'apple',
        model: 'iphone 12',
        img: 'https://asset1.ee.co.uk/medias/iphone-12-5g-blue-mobile-detail-1-Format-480?context=bWFzdGVyfHJvb3R8MzA4NjMzfGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaGZhL2g4Yy85NTY3NzM5NDQ1Mjc4L2lwaG9uZS0xMi01Zy1ibHVlLW1vYmlsZS1kZXRhaWwtMV9Gb3JtYXQtNDgwfDhjZTFjMDZjNzgyMWNiYjA2MGI4MWZlYzEwZGQ4MmNmMzU2NmVjN2IyNDcyYTg4ZjA1OGEyNmExNWI3ZmFhNzA',
        desc: '5G speed. A14 Bionic, the fastest chip in a smartphone. An edge-to-edge OLED display. Ceramic Shield with four times better drop performance. And Night mode on every camera. iPhone 12 has it all.',
        price: 799.99,
    },
    {
        id: 4,
        manufacturer: 'apple',
        model: 'iphone 12 pro',
        img: 'https://asset1.ee.co.uk/medias/detail1-iPhone-12-Pro-5G-128GB-Silver-mobile-Format-480?context=bWFzdGVyfHJvb3R8MjUxMjQ5fGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaDc4L2hkYi85NTQ2NTk5Mzk5NDU0L2RldGFpbDEtaVBob25lIDEyIFBybyA1RyAxMjhHQiBTaWx2ZXItbW9iaWxlX0Zvcm1hdC00ODB8YjExM2ZiZTdlMGFjOGU2MjNjMTY2ODg0MzhkMDVkYmFhOTY0YjY4M2E4NWZmNjYwMjMyMjUzNzQzNzE5N2UxMg',
        desc: 'It’s a leap year. 5G goes Pro. A14 Bionic rockets past every other smartphone chip. The Pro camera system takes low-light photography to the next level — with an even bigger jump on iPhone 12 Pro Max. And Ceramic Shield delivers four times better drop performance. Let’s see what this thing can do.',
        price: 999.99,
    },
    {
        id: 5,
        manufacturer: 'apple',
        model: 'iphone 11',
        img: 'https://asset1.ee.co.uk/medias/iphone-11-nc-64gb-black-mobile1-Format-480?context=bWFzdGVyfHJvb3R8MTgwNDY3fGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaGMyL2gzMC85NTYzMjAyNTE5MDcwL2lwaG9uZS0xMS1uYy02NGdiLWJsYWNrLW1vYmlsZTFfRm9ybWF0LTQ4MHw4NDA0ZDdlZTg1YWI1NDI5OTlmYmVjZjQ3ZjA2ZGQ0MmU5MjFjOTdjNzM4OWY0YjE0MDNlZWM5NTQzNzc3OTJj',
        desc: 'Just the right amount of everything. A new dual camera system captures more of what you see and love. The fastest chip ever in a smartphone and all day battery life let you do more and charge less. And the highest quality video in a smartphone, so your memories look better than ever.',
        price: 599.99,
    },
    {
        id: 6,
        manufacturer: 'apple',
        model: 'iphone se',
        img: 'https://asset1.ee.co.uk/medias/iphone-se-2020-nc-64gb-black-mobile2-Format-480?context=bWFzdGVyfHJvb3R8MjA4MDYzfGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaGUyL2hiZS85NTU0MDc5MDIzMTM0L2lwaG9uZS1zZS0yMDIwLW5jLTY0Z2ItYmxhY2stbW9iaWxlMl9Gb3JtYXQtNDgwfDU1NjcyNTNmNDU3ODM3NGVkYzJmZGRkNzRjNTVjYjM3YzJlODkzNDUzNjU3ODIzYTUyNzA2NTA0MzVmNDdlNjQ',
        desc: 'Lots to love. Less to spend. iPhone SE packs our most powerful chip into our most popular size at our most affordable price. Its just what youve been waiting for.',
        price: 299.99,
    },
    {
        id: 7,
        manufacturer: 'samsung',
        model: 'galaxy s20',
        img: 'https://asset1.ee.co.uk/medias/samsung-galaxy-s20-5g-black-mobile-detail-1-Format-480?context=bWFzdGVyfHJvb3R8MzgzNjI4fGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaDE2L2g5YS85NTM5MjE0NDc1Mjk0L3NhbXN1bmctZ2FsYXh5LXMyMC01Zy1ibGFjay1tb2JpbGUtZGV0YWlsLTFfRm9ybWF0LTQ4MHwzOTc4ZmUwMTg5YTVmMmU1ZWU0MTgxZDRhZDhmNzgzYWNjOTM4YTBlOTAyZjRmN2MwOWVlM2Q5ZWU5M2NhNjhl',
        desc: 'Introducing the Galaxy S20+ 5G, the smartphone camera to end all cameras. With a stunning 64MP Telephoto Camera, 10MP Front Camera and 12MP Wide Camera, Galaxy S20+ 5G let’s you take pro-level shots in an instant.',
        price: 599.99,
    },
    {
        id: 8,
        manufacturer: 'samsung',
        model: 'galaxy a42',
        img: 'https://asset1.ee.co.uk/medias/samsung-galaxy-a42-5g-mobile-detail-1-Format-480?context=bWFzdGVyfHJvb3R8NTI2MTI5fGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaDE5L2hiNi85NTU1NDc0NTQ2NzE4L3NhbXN1bmctZ2FsYXh5LWE0Mi01Zy1tb2JpbGUtZGV0YWlsLTFfRm9ybWF0LTQ4MHw5N2MyYmMyYjZhZTkyNzU5YTVhMDQxMTQ0N2Y4ZmRiMGM4NDAwMGEyMjI3MzgwMzVhZGU4OWYyMjgwYTRmN2Zh',
        desc: 'Galaxy A42 5G unlocks the awesome power of 5G (1) network connectivity for everyone. Download a Full HD movie at speeds thatll simply blow your mind. Say goodbye to lag when video calling mates. And social butterflies can create instant #FOMO and share pics and videos in the blink of an eye. With the Galaxy A42 5G, you can do all the things you love, faster than ever. ',
        price: 299.99,
    },
    {
        id: 9,
        manufacturer: 'samsung',
        model: 'galaxy a21',
        img: 'https://asset1.ee.co.uk/medias/samsung-a21s-black-mobile-detail-1-Format-480?context=bWFzdGVyfHJvb3R8MzE4NTgwfGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaGJiL2g2YS85NTE5MDc0MTQ4MzgyL3NhbXN1bmctYTIxcy1ibGFjay1tb2JpbGUtZGV0YWlsLTFfRm9ybWF0LTQ4MHw5MWM3ZDM0NTlkZTFlMzVjZmY3N2RiYmYzMWZlMmYwZjI3MDEyZGM5Njk1ZmQwNzFmNDQ4ZmJlMjA5OTM4NzQ1',
        desc: 'The Samsung Galaxy A21s ticks so many boxes. Its 6.5 inchInfinity-O display is perfect for watching videos or browsing online. With minimal bezels, smooth curves and an ergonomic grip, it’s comfortable to hold, while the glossy hologram finish on the back makes it stand out.',
        price: 200.99,
    },
    {
        id: 10,
        manufacturer: 'samsung',
        model: 'galaxy z',
        img: 'https://images.samsung.com/is/image/samsung/uk/galaxy-note20/gallery/uk-galaxy-z-fold2-sm-f916-sm-f916bznabtu-frontmysticbronze-thumb-274139626',
        desc: 'The Galaxy Z Fold2s revolutionary free-stop Hideaway Hinge is designed to smooth is fold and unfold. Made from over 60 different components, its built for durability and resilience. ',
        price: 1799.99,
    },
    {
        id: 11,
        manufacturer: 'samsung',
        model: 'galaxy a71',
        img: 'https://images2.drct2u.com/pdp_main_tablet_x2/products/me/me878/s01me878500c.jpg',
        desc: 'Meet the screen with a lot less bezel, and a lot more view Behind Galaxy A71s symmetrically aligned 6.7" Infinity-O Display, Super AMOLED Plus color technology delivers real-to-life color in everything you watch and do—from gaming and movies, to web-surfing and multi-tasking. Start enjoying more of what you love, without the screen getting in your way.',
        price: 288.99,
    },
    {
        id: 12,
        manufacturer: 'samsung',
        model: 'galaxy a51',
        img: 'https://asset1.ee.co.uk/medias/samsung-galaxy-a51-black-mobile-detail1-Format-480?context=bWFzdGVyfHJvb3R8MzUxMDUyfGltYWdlL3BuZ3xzeXMtbWFzdGVyL3Jvb3QvaDkzL2g2Mi85NTY1NTcxNjc4MjM4L3NhbXN1bmctZ2FsYXh5LWE1MS1ibGFjay1tb2JpbGUtZGV0YWlsMV9Gb3JtYXQtNDgwfGU1ZmZkZWJjMzBjODdiZDFkMGM3ODAwMzUxMGQ4ZjliZDg5ZjVhMWQxYjM5NzA3OWM3ZDg0YzFlYWZkNTQ3NjU',
        desc: 'The Samsung Galaxy A51’s 48 MP rear camera and quad camera system lets you capture the world as you see it. Expect the clearest, most crisp pictures possible.',
        price: 329.99,
    },
    {
        id: 13,
        manufacturer: 'google',
        model: 'pixel 5',
        img: 'https://cdn.dxomark.com/wp-content/uploads/medias/post-72009/google_pixel_5_frontback.jpeg',
        desc: 'The Pixel 5 is constructed using a "100% recycled aluminum enclosure" and Gorilla Glass 6 for the screen.The housing has a thin coating of plastic, while the power button is anodized with a metallic finish. The bottom of the device has a USB-C connector which is used for charging and audio output. It has stereo speakers, one of which is an under display unit with the other speaker located to the right of the USB-C port. The back houses a capacitive fingerprint reader.',
        price: 599.99,
    }

];
export default products;